### ISSUE TITLE
Move to GitLab, Linking of accounts

### ISSUE THREAD

**Issue by Ablu** [mana/mana#42]
Hi,

Sorry for the mass notifications!

We are moving to GitLab. The import will keep all content, but issues, pullrequests and comments of people, who do not have their GitLab account linked to their corresponding GitHub account, will no longer be linked (instead my name will appear on it with a comment about the origin).

So: **If you want to keep being linked to issues after the move**, please register on GitLab and link your GitHub account before 21th Sep (Friday). After that we will import our projects to GitLab. **Linking after the import is done will not be possible!**

**If you do not care** there is no need to do anything. Thanks for contributing!

In case of any questions, please drop me a line at mail@ablu.org.

/cc @Ablu
@atheros
@Bertram25
@bjorn
@cjwillcock
@cody
@fatalfeel
@hasufell
@ibara
@iggyvolz
@Kenny690
@ko2fan
@lvshiling
@mgorny
@p-groarke
@Philipp-S
@Pihro
@Postremus
@seeseekey
@stefanbeller
@thomasleese

**Comment by bjorn** [comment]
Just out of plain convenience and habit, since I mostly work with GitHub anyway, I have unarchived this repository and am just pushing my current work here. If anybody else would like to contribute and objects to this, just let me know.

I've ported the Mana client to SDL2 and am trying to get it to be able to play TMW again. :-)

**Comment by Ratstail91** [comment]
Woah, blast from the past - it's amazing this project is still ticking over!

This was one of the inspirations for my own project called [Tortuga](https://github.com/krgamestudios/Tortuga), though that never reached a state beyond "empty multiplayer rooms".

A heck of a lot has happened in that time - good to see you're still around @bjorn!

**Comment by p-groarke** [comment]
Wow you guys are still working on this!? That's amazing. Best!

**Comment by bjorn** [comment]
Well, we were not working on this for over 10 years, but yeah, now I'm patching it up so that it can play The Mana World again. And I'd welcome any contribution, be it coding or testing! :-)

Just a small update, that development has now moved to the GitLab instance hosted by The Mana World, at https://git.themanaworld.org/mana/mana. This repository will stick around as a mirror.
